### ISSUE TITLE
exo does not respect $HOME

### ISSUE THREAD

**Issue by janoszen** [exoscale/cli#155]
Unfortunately it seems that exo does not respect the $HOME environment variable, which makes scripting a bit tricky.

**Comment by janoszen** [comment]
Yes.

1. Create an exoscale.toml in a non-standard directory
2. export HOME=/other/directory
3. Run exo (e.g. zone list)

This is needed when a script creates exoscale.toml temporarily to not leave
the credentials permanently on said machine.

**Comment by falzm** [comment]
OK thank you for explaining, this is indeed a bug. Thank you for reporting!

**Comment by greut** [comment]
@janoszen use XDG_CONFIG_HOME instead.

https://github.com/exoscale/cli/blob/53606fba7615fc5aa09b4df85a55b9784dac4f99/cmd/root.go#L188

**Comment by janoszen** [comment]
I can work around it, that’s not the problem, but it breaks convention.

**Comment by greut** [comment]
maybe `os.UserHomeDir`[1] leads to a better result that `User.HomeDir`[2]

1. https://godoc.org/os#UserHomeDir
2. https://godoc.org/os/user#User

**Comment by falzm** [comment]
> I can work around it, that’s not the problem, but it breaks convention.

Duly noted: I'll keep this change for an upcoming backward-incompatible release.

**Comment by pyr** [comment]
I took a look at it and according to XDG[1], home should be looked up when `$XDG_CONFIG_HOME` is not set. @janoszen If you use different directories I still recommend setting XDG_CONFIG_HOME instead of HOME otherwise you will have to create a `.config` directory in your other location.


[1]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by pierre-emmanuelJ** [comment]
Thanks @pyr 👍
