### ISSUE TITLE
Add recursive delete capability for "sos delete"

### ISSUE THREAD

**Issue by ste-m** [exoscale/cli#164]
As done for https://github.com/exoscale/cli/issues/59 the CLI misses the ability to recursively delete objects and, by consequence, non-empty buckets.

Dunno if a `--force` flag is suitable, worth maybe looking at the behaviour of other S3 compatible tools.

**Comment by falzm** [comment]
Thanks @ste-m, I will look into this.

**Comment by falzm** [comment]
It looks like there is no such thing as a recursive delete in the S3 API, absolute object path must be provided in order to delete it. I've been told that the SOS API supports S3's [Multiple Delete Object API](https://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html), and the library we currently use in `exo` supports it so it should be doable without too much hassle.

**Comment by ste-m** [comment]
Ah, ok! I took a shortcut in assuming that if such convenience was available in a tool as `s3cmd` then it would be part of the S3 API. The flag that prompted me to assume that is `--recursive`, that would allow something like

    s3cmd del --recursive s3://bucket-to-delete

https://s3tools.org/usage

**Comment by falzm** [comment]
Yes, but since we partially implement the S3 API I wasn't considering it was possible *de facto* ;)
