### ISSUE TITLE
API error when provisioning VMs with cloud-init

### ISSUE THREAD

**Issue by Daeinar** [exoscale/cli#329]
Hi exoscale team,

I've been running into an issue when provisioning VMs via cloud-init. 

The `cloud-init.yaml` config file I am using is:

```
#cloud-config
package_upgrade: true
packages:
  - aide
  - apt-show-versions
  - apt-listchanges
  - arpwatch
  - chkrootkit
  - debian-goodies
  - debsecan
  - debsums
  - fail2ban
  - libpam-cracklib
  - libpam-tmpdir
  - needrestart
  - resolvconf
  - rkhunter
  - sysstat
  - usbguard
write_files:
  - path: /etc/ssh/sshd/config
    content: |
      Include /etc/ssh/sshd_config.d/*.conf
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      X11Forwarding no
      PrintMotd no
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      AllowTcpForwarding no
      ClientAliveCountMax 2
      LogLevel VERBOSE
      Compression no
      MaxAuthTries 2
      MaxSessions 2
      PermitRootLogin no
      TCPKeepAlive no
      AllowAgentForwarding no
      PermitEmptyPasswords no
runcmd:
  - echo 'blacklist uas' >> /etc/modprobe.d/blacklist.conf
  - echo 'blacklist usb_storage' >> /etc/modprobe.d/blacklist.conf
  - echo 'nameserver 8.8.8.8' >> /etc/resolvconf/resolv.conf.d/tail
  - echo 'nameserver 8.8.4.4' >> /etc/resolvconf/resolv.conf.d/tail
  - resolvconf -u
  - sed -i -e '/^UMASK/s/^.*$/UMASK\t\t027/' /etc/login.defs
  - sed -i -e '/^PASS_MAX_DAYS/s/^.*$/PASS_MAX_DAYS\t99998/' /etc/login.defs
  - sed -i -e '/^PASS_MIN_DAYS/s/^.*$/PASS_MIN_DAYS\t1/' /etc/login.defs
  - sed -i -e 's/ENABLED=\"false\"/ENABLED=\"true\"/g' /etc/default/sysstat
  - service sysstat restart
  - systemctl enable arpwatch@eth0
  - systemctl start arpwatch@eth0
power_state:
  mode: reboot
  message: Restarting after setup
```

When trying to deploy it via
```
exo vm create myvm --cloud-init-file cloud-init.yaml
```
I get the following error:
```
error: failure Deploying "myvm": API error Unauthorized 401 (ServerAPIException 9999): unable to verify user credentials and/or request signature
```

The strange thing is that if you remove the `runcmd` or `write_files` parts then the deployment works in either case.

Do you have any idea what's going on here?

Thanks a lot in advance!

Philipp

**Comment by falzm** [comment]
Hi @Daeinar, thank you for reporting this issue. I can reproduce it on my end, so we'll investigate.

**Comment by falzm** [comment]
@Daeinar a fix is on the way: #330

**Comment by Daeinar** [comment]
@falzm Nice, thanks. Appreciate it!

**Comment by falzm** [comment]
@Daeinar we just released version 1.27.2 containing the fix to this issue.

**Comment by DecentAgeCoder** [comment]
The issue seems not to be fixed with version 1.32.2. 

The following calls works fine:
exo vm create --template "Linux Debian 10 (Buster) 64-bit" --service-offering "medium" --zone "ch-dk-2" "test-01"

But when I pass the path of my cloud-init.yml file:
exo vm create --template "Linux Debian 10 (Buster) 64-bit" --service-offering "medium" --zone "ch-dk-2" "test-02" --cloud-init-file "/tmp/cloud-init.yml"

..i still get the same error:
error: failure Deploying "ec-local-testnet-01": API error Unauthorized 401 (ServerAPIException 9999): unable to verify user credentials and/or request signature

The content of the cloud-init.yml file is valid, since I used the same content when I created the server instance through the exoscale portal.

Any solution for this issue?

**Comment by falzm** [comment]
@DecentAgeCoder can you please share your cloud-init file? It won't be possible to pinpoint the issue without it.

**Comment by DecentAgeCoder** [comment]
Since my cloud-init file contains sensitive data I can not provide the file. I could in some cases just remove certain lines it was working again. I tried to reproduce the error with some test content without any success.

My assumption without looking into the code is that the HTTP request gets corrupted due to certain special characters (or a sequence) in the base64 encoded user data leading to a 401 error. I doesn't seem to be caused by a size limitation on the request parameter (probably userdata) since I have tested it with a clound-init.yml that is 90KB in size.

I there a debug log that I can activate to analyze the outgoing HTTP request, so I can check the validity of the HTTP request?

Thanks for you support!

**Comment by falzm** [comment]
@DecentAgeCoder looks like you have opened a support ticket relating to this issue, you can safely provide your cloud-init.yml file over there.

Also, the content of the user-data configuration is compressed before it is sent over to the API, so any non-ASCII character present in it shouldn't cause this issue. If you want to see the network exchange between the CLI and the API, you can set the environment variable `EXOSCALE_TRACE=1`.

**Comment by DecentAgeCoder** [comment]
Thanks Marc! Yes that makes sense (regarding non-ASCII characters). 
I just sent the corresponding cloud-init.yml file together with the trace output to the exoscale support.

**Comment by DecentAgeCoder** [comment]
@falzm I just read the documentation regarding the service deployVirtualMachine on https://community.exoscale.com/api/compute/.

It clearly states that the size of the request parameter 'userdata' musn't exeed 2KB when using GET method. In my case it probably exceeds this limit. It hink that's a standard limit for a HTTP request aprameter.
I just checked the trace, the web service uses GET and not POST to call deployVirtualMachine.
Since the limit for POST calls are 32KB, switching from GET to POST for accessing deployVirtualMachine would probably resolve my issue.

**Comment by DecentAgeCoder** [comment]
I just checked the size of my base64 encoded string in the log trace. It is 3.6 KB in size. So it definitely exceeds the limit of 2 KB!

**Comment by falzm** [comment]
@DecentAgeCoder the underlying egoscale library switches to `POST` requests when the payload exceed 2048 bytes: https://github.com/exoscale/egoscale/blob/master/request.go#L336-L341

```
$ EXOSCALE_TRACE=1 exo vm create blah --cloud-init-file cloud-init.yml
12021/07/01 11:16:50 POST /v1 HTTP/1.1
Host: api.exoscale.com
Content-Length: 4150
Content-Type: application/x-www-form-urlencoded
User-Agent: egoscale/0.59.0 (go1.16.5; darwin/amd64)

apikey=EXOxxxxxxxxxxxxxxxxxxxxxxxxxx&command=deployVirtualMachine&expires=2021-07-01T11%3A26%3A50%2B0200&ip6=false&keypair=nAbTjbBLao8s5DMtiJydMrFbdVEH61hnxw5xN3WL6H7l%2FhrrxGCguLItjHrGHhHos06I5vI2lmQtrJZwDBCfRQ%3D%3D&name=blah&response=json&rootdisksize=50&serviceofferingid=b6e9d1e8-89fc-4db3-aaa4-9b4c5b1d0844&signature=UwEGPDiGeDUwtrpDOLjWwCIni%2F8%3D&signatureversion=3&templateid=a5ddefa9-7e98-40cb-94b3-e20348b878fa&userdata=H4sIAAAAAAAA%2F8xZ%2F28bN7L%2FPX%2FFPKdAkr6u1nYSJ0%2BAH6pz0jSomhp2cjk0DgSKHGlZc8kth5StIPDffuCXlXYlOXFwxaGL1lqSww8%2FMxzODDf3uTJeFNzomZzfc7LGT0bjEPZeemsaLH%2F3VvJq7x6vGkZ0JYb3APC6kRaHMGOK8J4ntBS6CxA4Y165%2BK5ZjUNwSKEJMLfGN1EsPAWQF2bdoCqixI4wMoQPD0bj8fHD0Xj8CN78djo6P3%2F%2FYjgajx98TEIVKjWEcip1OWVUpU6qJsy7ylj5CcXkEpedBR8QVQWKw6dPD%2F4PRqPR6OTxm0%2Fs5ED9%2FuL1wZu3L5%2BGvtcnWvh%2Fnh49f%2F%2F70R96f7Y%2FPpH73i6fMI5H0yfvL%2BX%2Bm%2Bc%2FHz39U6jHUbcfw58Brx50dK4NEk%2BMulYLT99yu%2ByytsO2YXbpnPHhQSBycPj4QexVhl9O2qF2sZafmDErNfv7EqSGUXVp%2FN%2BNYcP4JZtjdvYZk%2BpwynRsLGQdf1njCmeZpsZYV1TONRT7OSs4WidnkjOHuc9bFV%2Fm2jfzw%2FhKZuaumMWiCafPOolUcFPXJi2TT00BpFkjksnQFc4YlTCVnDasLpZ%2BKnmS9PqTbOKbbBybKqSiQUuSHOp0UhVNC4sK2VrFiW8Ec%2BH8Wt%2FtnFsm2l7rNa9FskV9KaSFooHSNAmUV7UR8OzZs3VXT6gU5korwwR1xIszePb0ya7xxkrtZrD3gagSHy806qCKgOPI5UJPmWbcSaPheK1n7ZWTYSP24P%2BhRMfLds%2FKP5hUA2U4SztAS3JYc6cgAfc31xnPKyhTpJRaupIcsw5FIQy%2FRFtITY4pxQKB1dZCMaPzMUQfGJYrfQZpzoCbulRS[...]
```

**Comment by ktomk** [comment]
@DecentAgeCoder: Would you please be so kind and provide status of your issue? How did you solve it? Are you using a work-around, if yes, which one?

> @DecentAgeCoder the underlying egoscale library switches to POST requests when the payload exceeds 2048 bytes

I also see that _and_ can confirm this is not causing the error. At least not mine (in reference: #358).

**Comment by DecentAgeCoder** [comment]
I have not yet had the chance to re-test the issue with the latest version. I can try to reproduce the issue and update the status of this issue until the end of this week.

**Comment by ktomk** [comment]
@DecentAgeCoder: Just an FYI update from recent progress in #358: Try with `exo compute instance create` instead of `exo vm create`. I could already see it working with the cloud-init userdata where `exo vm create` failed with the error (I just have a side-tracking issue getting it to work for my own migration due to temporary SSH-keys that are currently not create with it - and then I think it's all: #360). Maybe for you its even more straight forward out of the box already.
