### ISSUE TITLE
Restricted API keys should be able to detect themselves

### ISSUE THREAD

**Issue by jeffallen** [exoscale/cli#342]
I wanted to write a security safety check feature like, "on tool start, check that the API key currently in use is restricted as expected otherwise error and quit".

But the only way to know the restrictions of a given key are to execute with an API key which has the IAM access right. Which I do not want my restricted key to have, for obvious reasons.

Ideally what I'd like is to have the restrictions on the key visible in the output of "exo config show -O json", so my restricted user can run this tool and the tool can check that the user is restricted as expected.

cc @whotopia

**Comment by falzm** [comment]
Hi @jeffallen, this is more of an API problem than the CLI itself – after all, it's only an API client and if the credentials it's using don't have the permission to look up an IAM API key's details, then there nothing we can do at this level... I'll inquiring about this to my backend colleagues, to see if there is something that could be done API-side.

**Comment by falzm** [comment]
So after bring up this topic to my colleagues, the final answer is: "you can include the `getApiKey` permission to your restricted keys in order to be able to look up their supported permissions". From our API's perspective, it is not possible to give out information on an IAM API key without this permission, even for the caller's own API key.

Also, the `exo config show` is about the CLI-specific configuration and so it is not the place for displaying the current API key's permissions (`exo iam apikey show` is).

**Comment by jeffallen** [comment]
Thanks, but I don't see how to do this from the exoscale web UI. It only allows me to set API key restrictions it knows about, and it does not know about "getApiKey". Am I missing something?

**Comment by falzm** [comment]
The `getApiKey` permission is available under the *IAM* Service section:

<img width="1917" alt="Screenshot 2021-06-10 at 14 11 46" src="https://user-images.githubusercontent.com/1122379/121522967-f8024180-c9f5-11eb-9ca8-50c2e95cb518.png">

**Comment by falzm** [comment]
If you have more questions or issues to report on this topic, I suggest you open a support ticket from the portal.
